import { Gabarito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Looking For Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='`${gabarito.className}` bg-slate-800'>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
